[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
script = 'scripts/foundry'
cache_path  = 'forge-cache'
optimizer = true
optimizer-runs = 10_000
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
